### ISSUE TITLE
run the pick_and_place.py file

### ISSUE THREAD

**Issue by hideonbush-prog** [ron007d/ros_pick_and_place_simulation#2]
i tried to run the file but it seems that it can only spawn the model(cube)

"rosrun pick_and_place pick_and_place.py 
[ INFO] [1718621807.167142982]: Loading robot model 'sample_robot'...
[ INFO] [1718621807.168491508]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1718621808.467142103, 38.161000000]: Ready to take commands for planning group robot1.
[ INFO] [1718621809.110518016, 38.801000000]: Ready to take commands for planning group gripper1.
[INFO] [1718621809.111508, 0.000000]: Y position of the box x: -0.2
y: 0.7
z: 1
success: True
status_message: "SpawnModel: Successfully spawned entity"

"

it stop until here.
how can i excute it fully?
![Uploading Untitled 1.png…]()

**Comment by ron007d** [comment]
after running `demo_gazebo.launch` there is no open cv screen, that means its not able to detect the object

try running this
```console
rosrun pick_and_place live_object_detector.py
```
if it shows error then python packages are not installed correctly. There might be a conflict between pandas and numpy

**Comment by hideonbush-prog** [comment]
> after running `demo_gazebo.launch` there is no open cv screen, that means its not able to detect the object
> 
> try running this
> 
> ```
> rosrun pick_and_place live_object_detector.py
> ```
> 
> if it shows error then python packages are not installed correctly. There might be a conflict between pandas and numpy

![Screenshot from 2024-06-20 16-28-02](https://github.com/ron007d/ros_pick_and_place_simulation/assets/173054803/16111b48-3615-4844-983e-fbe9baa579d6)

i did like you ask me to, but it still doesnt run properly^

**Comment by ron007d** [comment]
oohh got it there is lighting error in gazebo with non GPU user 

1. go to scene
2. disable shadow
![image](https://github.com/ron007d/ros_pick_and_place_simulation/assets/78581592/e2bc7859-c132-402f-bf06-856151d5211b)


check if it works, if not then try to manually give the color in the live object detector

**Comment by hideonbush-prog** [comment]
it works!! thanks a lot.

**Comment by ron007d** [comment]
Thanks closing the issue
